import { PROFILE } from "./profile.js";

export const DOMAIN_ORDER = ["solarpunk", "construccion", "industrial", "future"];

export const DOMAINS = {
  solarpunk: {
    icon: "🌿",
    name: "SOLARPUNK COLOMBIA",
    desc: "Por aquí empecé: agua, energía y alimento regenerativos para Bogotá, monitoreados en tiempo real.",
    projects: [
      {
        id: "sol-terraza",
        fidelidad: { nivel: "B", nota: "Modelo heurístico del cultivo; umbrales agronómicos plausibles, sin validación.", hoja: "docs/supuestos/01-sol-terraza.md", caso: "docs/casos/01-sol-terraza.md" },
        emoji: "🌱",
        name: "SOL-TERRAZA DT",
        tag: "Agrotech · Solar · Neblina andina",
        short: "Torres hidropónicas en una terraza bogotana, con energía de un panel solar y agua atrapada de la neblina. Quise probar que un cultivo urbano puede gastar 90 % menos agua que el suelo.",
        long: "Este fue mi punto de partida. Un cultivo hidropónico de terraza con un panel de 400 Wp y mallas atrapanieblas, una tecnología que en los cerros de Bogotá tiene todo el sentido. Simulo las variables que un agricultor urbano vigilaría (temperatura, humedad, pH, conductividad, nivel del tanque, batería) y las reglas que escribí a partir del documento técnico: si el pH baja de 5,8 se dosifica KOH, si el tanque baja del 20 % se abre la válvula de red, y de noche el sistema entra en modo ahorro. Las plantas de la escena cambian de color según la severidad del estado. Es una simulación, no un despliegue real.",
        specs: [
          "Torre 1,5 m · 30 posiciones de cultivo · pH 5,8–6,5",
          "FV 400 Wp · MPPT 40 A · Batería AGM 200 Ah / 24 V",
          "Malla raschel: 3–5 L/m²/día de neblina capturada",
          "Reglas de decisión: dosificación de KOH por pH, válvula de red por nivel, modo ahorro nocturno",
        ],
        stack: ["React 19", "Vite", "Three.js", "JavaScript"],
        nivel: { p: "P1 → P2", txt: "El bucle que simulo es el del P1: temperatura, luz y pH, sensores de menos de $30.000 en Bogotá. Con el P2, la predicción de riego dejaría de estar escrita a mano y saldría de un modelo entrenado." },
        status: "dev",
        repo: PROFILE.github + "/portafolio-solarpunk",
        video: "",
        chips: ["temp", "ph", "soc"],
        kpi: { key: "irr", label: "Irradiancia", unit: " W/m²", dec: 0, good: (v) => v > 100 },
        action: { label: "🌫️ Activar neblina andina", cmd: "fog" },
        vars: [
          { key: "temp", label: "Temperatura aire", unit: "°C", dec: 1 },
          { key: "hum", label: "Humedad aire", unit: "%", dec: 0 },
          { key: "ph", label: "pH solución", unit: "", dec: 2 },
          { key: "ce", label: "CE solución", unit: "mS/cm", dec: 2 },
          { key: "nivel", label: "Nivel depósito", unit: "%", dec: 0 },
          { key: "irr", label: "Irradiancia", unit: "W/m²", dec: 0 },
          { key: "soc", label: "SoC batería FV", unit: "%", dec: 0 },
        ],
      },
      {
        id: "aqua-serve",
        fidelidad: { nivel: "B", nota: "Balance hídrico con física citada; lluvia sintética.", hoja: "docs/supuestos/02-aqua-serve.md", caso: "docs/casos/02-aqua-serve.md" },
        emoji: "💧",
        name: "AQUA SERVE DT",
        tag: "Data centers IA · Balance hídrico pluvial · DLC",
        short: "Un datacenter de IA enfriado por líquido en Bogotá, donde el agua lluvia de la cubierta paga parte del agua de enfriamiento. Los números que persigo: PUE ≤ 1,15 y qué fracción del enfriamiento cubre la lluvia.",
        long: "Aquí junté dos cosas que me obsesionan: los datacenters de IA que están llegando a Colombia y el agua lluvia que dejamos ir. El eje es el agua, no la energía: modelo cuántos litros capta la cubierta (área × lluvia × coeficiente de escorrentía) frente a los litros que demanda el circuito de enfriamiento, calculados con el WUE (el agua por kWh de cómputo), y qué fracción de esa demanda paga la lluvia. Las turbinas en los bajantes existen, pero soy honesto con su tamaño: cuatro de 15 a 45 W dan unos 180 W pico, menos del 0,1 % del consumo eléctrico del datacenter; son un detalle anecdótico, no una fuente de energía. Lo que de verdad importa es el balance hídrico y el PUE, que con enfriamiento líquido directo sí baja de 1,15.",
        specs: [
          "Balance hídrico: captación pluvial (cubierta × lluvia × escorrentía) vs. demanda de enfriamiento",
          "Demanda por WUE (Water Usage Effectiveness); referencia 1,0 L/kWh (promedio industria ~1,8; mejores <0,2)",
          "DLC monofásico · ΔT 10–12 °C · PUE objetivo ≤ 1,15 (alcanzable con líquido directo)",
          "Turbina helicoidal AISI 316L · 15–45 W por bajante · ~0,1 % del consumo (anecdótico)",
          "Filtración: sedimentación → GAC → 5 µm → UV 254 nm",
        ],
        stack: ["React 19", "Vite", "Three.js", "JavaScript"],
        nivel: { p: "P2", txt: "Giré el eje de energía a agua a propósito: presumir 180 W de turbinas frente a un datacenter de decenas de kW habría sido deshonesto. El balance hídrico y el PUE sí son métricas que un operador mira. Le falta el histórico del P2: un balance sin serie temporal no le sirve a nadie." },
        status: "dev",
        repo: PROFILE.github + "/portafolio-solarpunk",
        video: "",
        chips: ["balanceHid", "cobertura", "pue"],
        kpi: { key: "balanceHid", label: "Balance hídrico", unit: " L/día", dec: 0, good: (v) => v >= 0 },
        action: { label: "🌧️ Simular lluvia", cmd: "rain" },
        vars: [
          { key: "balanceHid", label: "Balance hídrico (captado − demanda)", unit: " L/día", dec: 0 },
          { key: "captacionDia", label: "Captación pluvial", unit: " L/día", dec: 0 },
          { key: "demandaDia", label: "Demanda de enfriamiento (WUE)", unit: " L/día", dec: 0 },
          { key: "cobertura", label: "Demanda cubierta por lluvia", unit: "%", dec: 0 },
          { key: "pue", label: "PUE", unit: "", dec: 2 },
          { key: "tcpu", label: "T° CPU/GPU", unit: "°C", dec: 0 },
          { key: "nivel", label: "Nivel depósito pluvial", unit: "%", dec: 0 },
          { key: "rain", label: "Lluvia", unit: " mm/h", dec: 0 },
          { key: "pot", label: "Turbinas (anecdótico)", unit: " W", dec: 0 },
          { key: "turbPct", label: "Aporte turbinas vs. consumo", unit: "%", dec: 2 },
        ],
      },
    ],
  },
  industrial: {
    icon: "🌱",
    name: "INDUSTRIA VIVA",
    desc: "El mismo músculo técnico de la industria 4.0 (máquinas de estados ISA-88, coordinación de flota, diseño paramétrico) puesto al servicio de los animales, el hambre y lo vivo. Mismo stack, causa distinta.",
    projects: [
      {
        id: "cobot",
        fidelidad: { nivel: "B", nota: "Valores U reales (ISO 6946 + literatura); sin validar en cajas.", hoja: "docs/supuestos/04-refugio-vivo.md", caso: "docs/casos/04-refugio-vivo.md" },
        emoji: "🏠",
        name: "REFUGIO VIVO DT",
        tag: "Refugios modulares · Materiales reciclados · Confort térmico",
        short: "Le doy un lote, el clima y un inventario de materiales reciclados, y diseña refugios para animales rescatados: dimensiones, confort térmico de 24 horas, presupuesto y cronograma.",
        long: "Este gemelo une bienestar animal y economía circular. Le paso un lote, el clima real de la zona y un inventario de materiales reciclados (contenedores en desuso, madera de demolición, guadua, llantas, adobe) y me devuelve un diseño: dimensiones óptimas de refugio por especie, una curva de temperatura interior de 24 horas según el material del techo, un presupuesto en pesos y un cronograma. La clave está en el material: un techo de acero convierte el refugio en un horno al mediodía (37 °C), uno de guadua lo mantiene estable (27 °C). Y esos números ya no son inventados: salen de un balance sol-aire con valores U reales de literatura (guadua U≈0,9 vs acero U≈6 W/m²K). Con lo que desechamos, construimos dignidad para los animales rescatados. Es una simulación, no un despliegue real.",
        specs: [
          "Diseño paramétrico: dimensiones óptimas por especie (gallinas, cerdos, cabras, ovejas)",
          "Modelo térmico con U reales (ISO 6946 + sol-aire): guadua U≈0,9 vs acero U≈6 W/m²K",
          "Materiales reciclados con precio real en Colombia: contenedor, madera, guadua, llantas, adobe",
          "Comparación de materiales de techo: guadua vs acero, con curva de temperatura de 24 h",
          "Cambiar material, especies o ciudad y recalcular el diseño en vivo",
        ],
        stack: ["React 19", "Vite", "Three.js", "JavaScript"],
        nivel: { p: "P2 → P4", txt: "El cálculo térmico es estacionario (no CFD ni inercia térmica), pero ahora usa valores U reales de literatura, así que compara diseños con base física, no con factores inventados. Falta el clima por API según coordenadas y validar los dos supuestos (U_g, q_int) contra el experimento de las cajas. Los precios de materiales sí son reales." },
        status: "dev",
        repo: PROFILE.github + "/portafolio-solarpunk",
        video: "",
        chips: ["confort", "tint", "costo"],
        kpi: { key: "confort", label: "Confort", unit: " %", dec: 0, good: (v) => v >= 60 },
        action: { label: "🔁 Cambiar material del techo", cmd: "maint" },
        vars: [
          { key: "clock", label: "Hora del día", unit: "", dec: 0 },
          { key: "tint", label: "Temp. interior (refugio 1)", unit: "°C", dec: 1 },
          { key: "confort", label: "Refugios en rango ideal", unit: "%", dec: 0 },
          { key: "techo", label: "Material del techo", unit: "", dec: 0 },
          { key: "area", label: "Área usada", unit: "m²", dec: 0 },
          { key: "costo", label: "Costo total", unit: " M COP", dec: 1 },
          { key: "semanas", label: "Construcción", unit: " sem", dec: 0 },
        ],
      },
      {
        id: "linea-viva",
        fidelidad: { nivel: "B", nota: "ISA-88 real implementado; cinética heurística (Monod pendiente).", hoja: "docs/supuestos/05-fermenta-viva.md", caso: "docs/casos/05-fermenta-viva.md" },
        emoji: "🧫",
        name: "FERMENTA VIVA DT",
        tag: "Fermentación de precisión · ISA-88 · Proteína sin vaca",
        short: "Un biorreactor que produce la proteína de la leche (caseína) sin la vaca, gobernado por la misma familia de estándares (ISA-88) con la que hablan los bioprocesos reales.",
        long: "El corazón de este gemelo es una máquina de estados ISA-88, la familia de control por lotes (a la que pertenece PackML, ISA-TR88.00.02) que es el estándar real de los bioprocesos y la fermentación. Corre las fases de una fermentación fed-batch: Inoculación, Crecimiento exponencial, Producción, Cosecha y CIP (limpieza), con aborto por contaminación. El número estrella es el título de proteína por lote, que traduzco a litros de leche animal no necesarios y vacas ahorradas al año. Referentes reales como Perfect Day ya hacen esto a escala. Es una simulación, no un despliegue real.",
        specs: [
          "Máquina de estados fed-batch ISA-88: Inoculación → Crecimiento → Producción → Cosecha → CIP",
          "Variables de bioproceso: OD (biomasa), título g/L, pH, oxígeno disuelto, T°, feed",
          "Detección de contaminación que aborta el lote",
          "Productividad del lote en vez de OEE",
          "Impacto: litros de leche evitados y vacas ahorradas al año",
        ],
        stack: ["ISA-88 · S88 batch", "React 19", "Three.js", "JavaScript"],
        nivel: { p: "P3 → P5", txt: "La máquina de estados ISA-88 que corre aquí es real y está bien puesta. Lo honesto: no hay un biorreactor al otro lado, y el título de proteína es una curva que yo escribí, no un ensayo de laboratorio. Un biorreactor real publicando sus fases es el P3; que hable OPC UA con un MES sin traductor es el P5." },
        status: "dev",
        repo: PROFILE.github + "/portafolio-solarpunk",
        video: "",
        chips: ["titulo", "od", "fase"],
        kpi: { key: "titulo", label: "Título de proteína", unit: " g/L", dec: 1, good: (v) => v >= 8 },
        action: { label: "🧫 Inyectar contaminación", cmd: "fault" },
        vars: [
          { key: "fase", label: "Fase de bioproceso", unit: "", dec: 0 },
          { key: "titulo", label: "Título de proteína", unit: "g/L", dec: 2 },
          { key: "od", label: "Biomasa (OD600)", unit: "", dec: 2 },
          { key: "ph", label: "pH", unit: "", dec: 2 },
          { key: "do2", label: "Oxígeno disuelto", unit: "%", dec: 0 },
          { key: "temp", label: "Temp. del biorreactor", unit: "°C", dec: 1 },
          { key: "leche", label: "Leche animal evitada", unit: "L", dec: 0 },
        ],
      },
      {
        id: "almacen-smart",
        fidelidad: { nivel: "C", nota: "Lógica de flota razonable, pero todo es criterio propio. En standby.", hoja: "docs/supuestos/06-abasto-vivo.md", caso: "docs/casos/06-abasto-vivo.md" },
        emoji: "🍞",
        name: "ABASTO VIVO DT",
        tag: "Banco de alimentos · Flota AMR · FEFO",
        short: "Una flota de 5 robots moviendo comida donada en un banco de alimentos: priorizan lo que está por vencer para que llegue a la gente antes de dañarse.",
        long: "Quería una flota trabajando por algo que me importa: un banco de alimentos (como ABACO o el Banco de Alimentos de Bogotá) rescata comida donada antes de que se dañe y la lleva a quien la necesita, atacando el desperdicio y el hambre a la vez. Cinco AMRs navegan entre los racks, cada uno con su batería y sus decisiones: cuando uno baja del 20 % se va a cargar solo, y cuando bloqueas un pasillo recalculan la ruta. La vuelta que le da alma es la perecibilidad FEFO (First Expired, First Out): la flota prioriza los lotes por vencer. La meta son raciones despachadas y kilos rescatados del desperdicio. Es una simulación, no un despliegue real.",
        specs: [
          "5 AMRs · carga 50 kg · recarga automática bajo 20 % · recálculo de ruta",
          "Perecibilidad FEFO: la flota prioriza los lotes por vencer",
          "Raciones despachadas/hora (meta >150) y kg rescatados del desperdicio",
          "Alerta de lotes en riesgo de vencer sin despachar",
          "Verificación por barcode en el muelle de despacho",
          "Contexto real: ABACO · Banco de Alimentos de Bogotá",
        ],
        stack: ["React 19", "Vite", "Three.js", "JavaScript"],
        nivel: { p: "P3 → P4", txt: "Cinco robots con estado, batería y posición son cinco Things: ese es exactamente el caso de uso de Ditto en el P3. La navegación con LIDAR y evitación real de colisiones es P4. La capa FEFO es lógica de negocio honesta sobre la simulación." },
        status: "dev",
        repo: PROFILE.github + "/portafolio-solarpunk",
        video: "",
        chips: ["thr", "kg", "vencer"],
        kpi: { key: "thr", label: "Raciones despachadas", unit: " rac/h", dec: 0, good: (v) => v >= 150 },
        action: { label: "🍞 Despachar 100 raciones", cmd: "burst" },
        vars: [
          { key: "thr", label: "Raciones por hora", unit: "rac/h", dec: 0 },
          { key: "pend", label: "Lotes pendientes", unit: "uds", dec: 0 },
          { key: "compl", label: "Raciones despachadas", unit: "uds", dec: 0 },
          { key: "kg", label: "Kg rescatados", unit: "kg", dec: 0 },
          { key: "vencer", label: "Lotes por vencer", unit: "uds", dec: 0 },
          { key: "activos", label: "AMR operativos", unit: "/5", dec: 0 },
          { key: "bat", label: "Batería media de flota", unit: "%", dec: 0 },
        ],
      },
    ],
  },
  construccion: {
    icon: "🏗️",
    name: "CONSTRUCCIÓN",
    desc: "Me metí a la obra: seguridad, economía circular y edificios net-zero, en el sector que mueve el 9 % del PIB del país.",
    projects: [
      {
        id: "obra-viva",
        fidelidad: { nivel: "B", nota: "Cada umbral cita norma (DIN, Res., NSR-10, ISO). Falta histórico de obra.", hoja: "docs/supuestos/07-obra-viva.md", caso: "docs/casos/07-obra-viva.md" },
        emoji: "🏗️",
        name: "OBRA-VIVA DT",
        tag: "SST · Vibración · Aire · Geotecnia",
        short: "Una obra vigilada de verdad: vibración, ruido, polvo, nivel freático y calor sobre la cuadrilla, cada uno con su norma y su alerta.",
        long: "Este lo armé pensando en las obras que uno ve en Bogotá: quejas por vibración, polvo en las ventanas, ruido a deshoras. El diseño es una red LoRaWAN de postes perimetrales; aquí simulo sus reglas, y no me las inventé: aspersión automática si el PM10 pasa de 150 µg/m³ sostenido, rotación de cuadrilla si el índice WBGT supera los 30 °C (ISO 7243), vibración medida contra la DIN 4150-3 que protege las fachadas vecinas, y protocolo de paralización si el inclinómetro del talud acumula más de 25 mm en 24 horas. La escena pinta el riesgo de cada zona en un mapa de calor 3D.",
        specs: [
          "Vibración PPV: umbral 25 mm/s sensible · 50 mm/s robusta (DIN 4150-3)",
          "Ruido: 85 dB(A) TWA 8 h ocupacional (Res. 1792/1990) · 65/55 dB(A) comunitario (Res. 0627/2006)",
          "PM10 > 150 µg/m³ 24 h (Res. 2254/2017) → aspersión 2–4 L/min por boquilla",
          "Inclinómetro ±0,01° · amarilla >15 mm/24 h · roja >25 mm/24 h (NSR-10 Título H)",
          "WBGT ISO 7243 · rotación obligatoria sobre 30 °C",
          "LoRaWAN 915 MHz (2–5 km urbano) → Mosquitto → InfluxDB → Grafana + Unity",
        ],
        stack: ["React 19", "Vite", "Three.js", "JavaScript"],
        nivel: { p: "P1 → P3", txt: "Es una red, no un dispositivo: ocho postes perimetrales son ocho Things de Ditto, que es el P3. Los sensores individuales de vibración y PM10 ya son alcanzables desde el P1." },
        status: "spec",
        repo: PROFILE.github + "/portafolio-solarpunk",
        video: "",
        chips: ["ppv", "ruido", "pm10"],
        kpi: { key: "pm10", label: "PM10", unit: " µg/m³", dec: 0, good: (v) => v < 150 },
        action: { label: "🔨 Activar pilotadora (frente norte)", cmd: "pile" },
        vars: [
          { key: "ppv", label: "Vibración PPV", unit: "mm/s", dec: 1 },
          { key: "ruido", label: "Ruido Leq", unit: "dB(A)", dec: 1 },
          { key: "pm10", label: "Material particulado PM10", unit: "µg/m³", dec: 0 },
          { key: "pm25", label: "Material particulado PM2.5", unit: "µg/m³", dec: 0 },
          { key: "desp", label: "Desplazamiento inclinómetro", unit: "mm/24 h", dec: 1 },
          { key: "freat", label: "Nivel freático", unit: "m", dec: 2 },
          { key: "wbgt", label: "Índice WBGT", unit: "°C", dec: 1 },
        ],
      },
      {
        id: "solar-edificio",
        fidelidad: { nivel: "B", nota: "Modelo FV simplificado; puede usar irradiancia real de Bogotá (PVGIS).", hoja: "docs/supuestos/09-solar-edificio.md", caso: "docs/casos/09-solar-edificio.md" },
        emoji: "🌡️",
        name: "SOLAR-EDIFICIO DT",
        tag: "Net Zero · irradiancia real PVGIS · EDGE / LEED",
        short: "Un edificio bajo el sol de Bogotá: irradiancia real del año meteorológico típico de PVGIS (conmutable con la sintética), generación fotovoltaica, ventilación cruzada y el balance generación − consumo latiendo en vivo.",
        long: "Para este no quise inventarme el sol: el gemelo puede alimentarse con la irradiancia real de Bogotá (año meteorológico típico de PVGIS), conmutable con la sintética. El modelo es deliberadamente sencillo y honesto: una curva solar aproximada, un modelo fotovoltaico con derrateo por temperatura (−0,35 %/°C), un nodo térmico que resuelve la temperatura interior y un modelo de ventilación natural donde abrir las ventanas cambia las renovaciones de aire y el efecto se ve en el balance en segundos. El diseño real leería el inversor por Modbus TCP y medidores por circuito; aquí esos equipos los interpreta el simulador, dentro del marco de la CREG 030 para autogeneración.",
        specs: [
          "Irradiancia real: TMY horario de PVGIS v5.2 para Bogotá, conmutable con la sintética",
          "Modelo térmico de un nodo · ventilación natural por ACH · envolvente ref. NTC 6083",
          "Renovaciones de aire 0,6 base / 4,6 con ventilación cruzada",
          "FV ~12,5 kWp · derrateo térmico −0,35 %/°C · temperatura de celda tipo NOCT · 97,5 % otras pérdidas",
          "Soporte EDGE / créditos LEED · RETIE · Res. 30366/2020 CREG · Ley 1715/2014",
        ],
        stack: ["React 19", "Vite", "Three.js", "JavaScript"],
        nivel: { p: "P2 → P7", txt: "El gemelo puede alimentarse con la irradiancia real de Bogotá (TMY de PVGIS), conmutable con la sintética. El recurso solar es una curva aproximada; el siguiente paso sería la posición solar con NREL SPA y la transposición de Perez. El inversor por Modbus es el P1, el histórico el P2, y venderlo a una constructora sobre Azure el P7." },
        status: "spec",
        repo: PROFILE.github + "/portafolio-solarpunk",
        video: "",
        chips: ["balance", "fv", "tin"],
        kpi: { key: "balance", label: "Balance neto", unit: " kW", dec: 2, good: (v) => v > 0 },
        action: { label: "🪟 Abrir ventanas (ventilación cruzada)", cmd: "vent" },
        toggle: { title: "Fuente de irradiancia", label: "Irradiancia", cmd: "tmyReal", on: "TMY real (PVGIS)", off: "sintética" },
        vars: [
          { key: "irr", label: "Irradiancia sobre cubierta", unit: "W/m²", dec: 0 },
          { key: "fv", label: "Generación fotovoltaica", unit: "kW", dec: 2 },
          { key: "cons", label: "Consumo total", unit: "kW", dec: 2 },
          { key: "balance", label: "Balance neto (FV − consumo)", unit: "kW", dec: 2 },
          { key: "tin", label: "Temperatura interior", unit: "°C", dec: 1 },
          { key: "text", label: "Temperatura exterior", unit: "°C", dec: 1 },
          { key: "ach", label: "Renovaciones de aire", unit: "ACH", dec: 2 },
          { key: "soc", label: "SoC batería LFP", unit: "%", dec: 0 },
        ],
      },
    ],
  },
  future: {
    icon: "🏙️",
    name: "SMART CITY · BOGOTÁ",
    desc: "Gemelos digitales para los problemas que la ciudad vive cada año: hoy, el agua lluvia. Mañana, movilidad y redes.",
    projects: [
      {
        id: "canal-alerta",
        fidelidad: { nivel: "B", nota: "Usa lluvia real de IDEAM (Kennedy); modelo de embalses ilustrativo.", hoja: "docs/supuestos/10-canal-alerta.md", caso: "docs/casos/10-canal-alerta.md" },
        emoji: "⛈️",
        name: "CANAL-ALERTA DT",
        tag: "Drenaje urbano · Lluvia real IDEAM · Alerta temprana",
        short: "Una cuenca de drenaje bogotana bajo aguacero: sumideros que se tapan con basura, un humedal que amortigua y una alerta que corre contra el nivel del canal, alimentada con lluvia real de IDEAM.",
        long: "Cada temporada de lluvias, Bogotá repite la misma escena: aguaceros cortos e intensos, sumideros tapados por basura, canales al límite y barrios de Kennedy o Bosa con el agua adentro. Este gemelo modela esa cadena completa: la lluvia entra por los sumideros (si la basura los deja), el humedal y los SUDS amortiguan lo que pueden, y el nivel del canal decide la alerta. La variable que casi nadie modela y aquí es protagonista: la basura. La capacidad de los sumideros cae a medida que se acumula, y una cuadrilla de despeje la recupera. La alerta temprana calcula cuántos minutos quedan antes del desborde al ritmo actual de entrada, que es el número que le importa a quien tiene que evacuar un sótano o cerrar una vía. Y la lluvia que alimenta todo esto ya no es inventada: corre sobre la serie horaria real de la estación IDEAM de Kennedy (oct–nov 2024), con sus aguaceros vespertinos de verdad.",
        specs: [
          "Lluvia de entrada: serie horaria real de IDEAM (estación Kennedy, oct–nov 2024)",
          "Cadena hidráulica completa: lluvia → sumideros → SUDS/humedal → canal",
          "Sumideros con obstrucción progresiva por basura y despeje por cuadrilla",
          "Alerta de 4 niveles por umbral de nivel del canal, con minutos de anticipación al desborde",
          "SUDS (norma NS-166 de la EAAB) y humedal urbano como amortiguadores con capacidad finita",
          "Modelo pensado como entidades NGSI-LD: cuenca, sumidero, humedal y alerta como entidades FIWARE",
        ],
        stack: ["React 19", "Vite", "Three.js", "JavaScript"],
        nivel: { p: "P2 → P5", txt: "La hidrología es series de tiempo o no es nada: por eso la lluvia de entrada ya es real (serie horaria de IDEAM, Kennedy). Falta el nivel del canal medido para cerrar el lazo (P2), una red de sensores por la cuenca como flota (P3) y hablar NGSI-LD sobre FIWARE, el estándar de facto de las ciudades inteligentes (P5). IDIGER ya opera un sistema de alerta real; este gemelo es la maqueta de cómo se le agrega la capa de decisión." },
        status: "spec",
        repo: PROFILE.github + "/portafolio-solarpunk",
        video: "",
        nota: "Este gemelo usa datos históricos reales de IDEAM (estación Kennedy, oct–nov 2024).",
        chips: ["nivel", "lluvia", "anticipa"],
        kpi: { key: "nivel", label: "Nivel del canal", unit: " %", dec: 1, good: (v) => v < 75 },
        action: { label: "⛈️ Simular aguacero (40 mm/h)", cmd: "storm" },
        vars: [
          { key: "lluvia", label: "Lluvia (serie real IDEAM)", unit: "mm/h", dec: 1 },
          { key: "fechaSerie", label: "Fecha de la serie", unit: "", dec: 0 },
          { key: "nivel", label: "Nivel del canal", unit: "%", dec: 1 },
          { key: "alerta", label: "Alerta de cuenca", unit: "", dec: 0 },
          { key: "anticipa", label: "Anticipación al desborde", unit: "min", dec: 0 },
          { key: "sumid", label: "Capacidad de sumideros", unit: "%", dec: 0 },
          { key: "amort", label: "Amortiguado por humedal + SUDS", unit: "m³", dec: 0 },
          { key: "basura", label: "Basura retirada hoy", unit: "kg", dec: 0 },
        ],
      },
    ],
  },
};
