/* ================= RUTA DE 5 AÑOS · 2026 → 2031 ================= */
// Progreso: 0 = P1 en curso · 1 = P1 hecho y P2 en curso · 7 = ruta completa.
export const RUTA_ACTUAL = 0;

export const RUTA = [
  {
    n: 1,
    emoji: "🛏️",
    name: "El bucle completo, mínima complejidad",
    tag: "Sensor real → MQTT → lógica → 3D",
    dif: 1,
    tiempo: "4–6 semanas",
    inversion: "$65.000–$80.000 COP en hardware",
    construyo: "Un gemelo de mi propio escritorio: un ESP32 con sensores de temperatura, humedad y luz publicando por MQTT, procesados en Python, pintando una escena en Blender que reacciona en segundos.",
    porque: "Necesito una victoria temprana que integre el bucle completo con la mínima complejidad posible. Elegí mi cuarto y no algo más ambicioso justamente porque el sistema ya lo conozco: así el único problema difícil es el que vine a resolver, que es el flujo de datos. Ese bucle de sensor, transporte, lógica y visualización es la columna vertebral de los otros seis proyectos y de toda mi carrera.",
    demuestra: "Que puedo cerrar el ciclo físico-digital de punta a punta, no solo la parte visual.",
    desbloquea: "Es lo que le falta a los 8 gemelos del portafolio para dejar de ser simulación. Sol-Terraza y Obra-Viva son los candidatos inmediatos: la temperatura y la luz que hoy genero por código son sensores de $27.000 en Bogotá.",
    decision: "Compro DHT22 y BME280 a propósito. El BME280 es superior en todo: más preciso, añade presión y habla I2C. Pero el DHT22 me obliga a pelear con un protocolo digital difícil. Uno para aprender, otro para producción.",
    stack: ["ESP32", "DHT22", "BME280", "Arduino IDE 2.x", "Python 3.12", "paho-mqtt", "Mosquitto", "Blender 4.5 LTS"],
    entregable: "Repo con el sketch, el script y el .blend · video de 60–90 s donde soplar el sensor cambia la escena",
  },
  {
    n: 2,
    emoji: "🌱",
    name: "De mostrar el ahora a anticipar el futuro",
    tag: "Series temporales + primer modelo de ML",
    dif: 2,
    tiempo: "6–8 semanas",
    inversion: "+$17.732 COP (sensor capacitivo)",
    construyo: "Un gemelo de invernadero que guarda series temporales en InfluxDB, las expone en Grafana y predice con Machine Learning cuándo regar y cuándo va a subir la temperatura.",
    porque: "Un gemelo que solo refleja el presente es un tablero bonito. El valor real aparece cuando anticipa. Elegí agricultura y no otro dominio porque en Colombia no es un ejercicio teórico: somos el segundo exportador mundial de flores cortadas después de Países Bajos, con 344.000 toneladas y USD 2.439,5 millones exportados en 2025 según Asocolflores. Hay clientes reales al final de esta habilidad.",
    demuestra: "Persistencia de datos históricos, dashboards profesionales y capacidad predictiva. Es el salto del tablero al gemelo.",
    desbloquea: "Le da memoria y predicción a los 8. Hoy las sparklines del panel de detalle son memoria de sesión que se borra al recargar; con InfluxDB serían serie real. Y la predicción que hoy escribo por código pasaría a ser un modelo entrenado.",
    decision: "Sensor de humedad de suelo capacitivo v1.2, nunca resistivo: el resistivo se corroe en semanas y el dato se degrada sin avisar. Un gemelo alimentado por un sensor que miente es peor que no tener gemelo.",
    stack: ["InfluxDB 2.7 OSS", "Grafana", "scikit-learn", "Capacitivo v1.2", "ESP32", "Python"],
    entregable: "Dashboard con histórico · notebook con el modelo · artículo explicando la predicción",
  },
  {
    n: 3,
    emoji: "🔗",
    name: "De scripts caseros a framework profesional",
    tag: "Eclipse Ditto · el gemelo como entidad formal",
    dif: 3,
    tiempo: "8–10 semanas",
    inversion: "$0 · todo open source",
    construyo: "Una flota de dispositivos gestionados como «Things» formales en Eclipse Ditto, con ingestión MQTT, API REST y UI web consultable.",
    porque: "Mis dos primeros gemelos no escalan a cientos de dispositivos ni tienen modelo formal: son scripts. Ditto introduce el gemelo como entidad con estado, políticas de acceso y API, que es como lo entiende la industria. Es el punto donde dejo de improvisar arquitectura y adopto la que ya existe.",
    demuestra: "Que puedo trabajar con el framework que usa la industria, no solo con código propio.",
    desbloquea: "Abasto Vivo es exactamente el caso que Ditto resuelve: cinco AMRs con estado, batería y posición son cinco Things. Fermenta Viva encaja igual, porque un biorreactor publica su propia fase de bioproceso ISA-88. Y Obra-Viva también: una red LoRaWAN de sensores perimetrales es una flota, no un dispositivo.",
    decision: "Ditto y no una solución propia. Es el corazón de OpenTwins (Ditto + Hono + Kafka + InfluxDB + Grafana), así que aprenderlo me conecta con un ecosistema completo en vez de dejarme con una librería aislada.",
    stack: ["Eclipse Ditto 3.8.x", "Docker Compose", "MQTT", "REST API", "Eclipse Hono"],
    entregable: "Despliegue con ≥3 Things · conexión MQTT operativa · repo con el Docker Compose",
  },
  {
    n: 4,
    emoji: "🦾",
    name: "Robótica sin comprar una fábrica",
    tag: "ROS 2 · física simulada · detección de anomalías",
    dif: 4,
    tiempo: "10–12 semanas",
    inversion: "$0 en la ruta accesible",
    construyo: "Una línea de producción simulada que genera datos sintéticos de sus sensores, y un modelo de detección de anomalías entrenado sobre ese dataset.",
    porque: "Los gemelos industriales que quiero construir exigen simulación física y robótica, y no puedo comprar una celda robótica para practicar. Aquí lo aprendo en un entorno seguro y gratis. La detección de anomalías es además la base del mantenimiento predictivo, que es donde un gemelo justifica su costo ante un gerente de planta.",
    demuestra: "Simulación física real y ML aplicado a mantenimiento predictivo, no animación scripteada.",
    desbloquea: "Abasto Vivo da el salto más grande aquí: hoy sus cinco AMRs siguen una cuadrícula, con este proyecto navegarían con LIDAR de verdad y evitación de colisiones real. Y la detección de contaminación de Fermenta Viva pasaría de una curva que yo escribí a un modelo entrenado sobre datos del bioproceso.",
    decision: "Empiezo por ROS 2 Jazzy + Gazebo Harmonic, no por Isaac Sim. Gazebo corre en una laptop sin RTX; Isaac Sim exige GPU que hoy no tengo. Prefiero avanzar en la ruta accesible ahora y hacer la foto-realista después, que bloquearme esperando hardware.",
    stack: ["ROS 2 Jazzy", "Gazebo Harmonic", "Isaac Sim 5.x", "scikit-learn", "Python"],
    entregable: "Simulación funcional · dataset sintético · modelo de anomalías · video + repo",
  },
  {
    n: 5,
    emoji: "📐",
    name: "Lo que exigen gobiernos y grandes industrias",
    tag: "AAS (IEC 63278-1) · FIWARE NGSI-LD",
    dif: 4,
    tiempo: "10–12 semanas",
    inversion: "$0 · todo open source",
    construyo: "Un gemelo conforme a estándares: Asset Administration Shell con Eclipse BaSyx, y entidades NGSI-LD en FIWARE Orion-LD con Smart Data Models.",
    porque: "Hasta aquí todos mis gemelos son «míos»: funcionan, pero nadie más puede integrarlos. Los que compran gobiernos y grandes industrias tienen que ser interoperables por contrato. La AAS es EL estándar de Industria 4.0 europeo y NGSI-LD domina smart cities. Este es el proyecto que separa un portafolio de estudiante de una propuesta que una entidad puede firmar.",
    demuestra: "Que hablo el idioma normativo que exige un comprador institucional, no solo el técnico.",
    desbloquea: "Fermenta Viva es el caso más directo: hoy simulo ISA-88 y OPC UA, pero que un biorreactor y el MES de una planta se entiendan sin traductor es precisamente lo que este proyecto me enseña a montar. Canal-Alerta igual: al Distrito solo le sirve si la cuenca, los sumideros y las alertas son entidades NGSI-LD sobre FIWARE.",
    decision: "BaSyx Java V2 conforme a AAS v3, no la V1. Es la versión alineada con IEC 63278-1 y el proyecto está vivo: 872 commits en el último año. Un estándar sin mantenimiento es deuda técnica disfrazada de credencial.",
    stack: ["Eclipse BaSyx Java V2", "IEC 63278-1 (AAS v3)", "FIWARE Orion-LD 1.12.0", "NGSI-LD", "Docker"],
    entregable: "AAS con submodelos en BaSyx · entidades NGSI-LD en Orion-LD · visualización sobre ambos",
  },
  {
    n: 6,
    emoji: "☕",
    name: "PROYECTO ESTRELLA · El café colombiano foto-realista",
    tag: "Omniverse · OpenUSD · IA de series temporales",
    dif: 5,
    tiempo: "4–6 meses",
    inversion: "GPU RTX ≥16 GB VRAM, o GPU en la nube",
    construyo: "Un gemelo digital foto-realista de una línea de beneficio de café colombiano en NVIDIA Omniverse con OpenUSD, alimentado con IA de series temporales y datos de IoT real.",
    porque: "Es donde mi ventaja converge con todo lo demás. Vengo del diseño visual y el 3D: esa es la habilidad que la mayoría de ingenieros de datos no tiene, y hasta el P5 la tengo subutilizada. Aquí deja de ser un adorno y se vuelve el diferenciador. Elegí café y no cemento ni energía porque nadie más va a tener «el gemelo foto-realista del café colombiano», y porque el sector ya se está moviendo: Cenicafé investiga caficultura 4.0 y la Superintendencia de Industria y Comercio publicó un boletín sobre Industria 4.0 en el sector.",
    demuestra: "Foto-realismo de nivel industrial sobre un stack IoT/IA completo, con una historia local que nadie puede copiar.",
    desbloquea: "Es el salto estético de todo el portafolio. Los 8 gemelos están hechos con primitivas de Three.js: cubos, cilindros y conos. Funcionan como demostración de lógica, pero son geometría, no materiales. Omniverse es donde el argumento visual se vuelve incontestable.",
    decision: "El Omniverse Launcher quedó deprecado en octubre de 2025: voy por kit-app-template desde GitHub o el NGC Catalog. Trabajar sobre una herramienta deprecada es empezar el proyecto insignia con fecha de vencimiento.",
    stack: ["NVIDIA Omniverse", "OpenUSD", "Blender 4.5 LTS", "RTX 40-series", "Python"],
    entregable: "Gemelo navegable con datos reales y predichos · video cinematográfico · artículo técnico · charla en conferencia",
  },
  {
    n: 7,
    emoji: "🌐",
    name: "De estudiante a proveedor de soluciones",
    tag: "Azure Digital Twins · producción · cliente real",
    dif: 5,
    tiempo: "4–6 meses",
    inversion: "Pay-as-you-go · USD 200 de crédito inicial",
    construyo: "Un gemelo digital en producción para una empresa, gobierno u organización, desplegado en Azure Digital Twins con modelado DTDL.",
    porque: "Todo lo anterior es entrenamiento; esto es el juego real. Cambia lo que se me exige: ya no es que funcione, es que funcione bajo SLA, con seguridad, escalabilidad y alguien que depende del resultado. Es también el único proyecto que valida los seis anteriores, porque un cliente pagando es la única prueba de que el trabajo servía para algo fuera de mi cuarto.",
    demuestra: "Que puedo entregar bajo requisitos, seguridad y responsabilidad frente a un tercero, con ROI medible.",
    desbloquea: "Cualquiera de los 8, con un cliente detrás. Solar-Edificio y Abasto Vivo son los más listos: uno le habla a una constructora con certificación EDGE, el otro a un banco de alimentos que necesita mover donaciones antes de que venzan.",
    decision: "Azure Digital Twins, no AWS. AWS IoT TwinMaker entró en mantenimiento y no acepta clientes nuevos desde el 30 de julio de 2026. Construir el primer proyecto con cliente sobre una plataforma descontinuada sería un error de criterio, no de código. Azure cobra USD 1 por millón de operaciones de API y USD 2,50 por millón de mensajes.",
    stack: ["Azure Digital Twins", "DTDL", "Azure IoT Hub", "Azure Data Explorer", "Python"],
    entregable: "Solución en producción · contrato o carta del cliente · caso de estudio",
  },
];
